- name: Add Confluent apt key
  apt_key:
    url: "{{confluent.repository.debian.key_url}}"
    state: present
    become: true
- name: Add Confluent apt repo
  apt_repository:
    repo: "{{confluent.repository.debian.repository}}"
    state: present
    become: true
- name: Install the Confluent Platform
  apt:
    name: "{{confluent.package_name}}"
    update_cache: yes
    become: true
